version: 2
updates:
  # 1) GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"      # Check for updates weekly
      day: "monday"           # (optional) set a specific day
    labels:
      - "dependency"
      - "actions"
    assignees:
      - "markcoleman"
    open-pull-requests-limit: 5

  # 2) NPM Dependencies (JavaScript/TypeScript)
  - package-ecosystem: "npm"
    directory: "/"            # If your package.json is at root; else adjust
    schedule:
      interval: "daily"       # Check for updates daily
    labels:
      - "dependency"
      - "npm"
    assignees:
      - "markcoleman"
    open-pull-requests-limit: 5
    # optionally ignore certain dev dependencies or pinned versions:
    # ignore:
    #   - dependency-name: "some-package"
    #     versions: "<=1.2.3"

  # 3) Dev Container References
  - package-ecosystem: "devcontainers"
    directory: "/"            # If your devcontainer.json is in root
    schedule:
      interval: "weekly"      # Check for updates weekly
    labels:
      - "dependency"
      - "devcontainer"
    assignees:
      - "markcoleman"
    open-pull-requests-limit: 3