name: CI - Validate & Report Tests

permissions:
  id-token: write
  contents: read
  checks: write

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.markdown'
      - '**.txt'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.github/*.md'
      - 'assets/**'
      - 'CODEOWNERS'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.markdown'
      - '**.txt'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.github/*.md'
      - 'assets/**'
      - 'CODEOWNERS'
      - '.vscode/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # or 18, etc.

      # 1) Cache Node modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          # 'path' is what we want to store in cache
          path: |
            node_modules
          # 'key' is a unique identifier for the cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          # 'restore-keys' is a fallback list in case the exact key isn't found
          restore-keys: |
            ${{ runner.os }}-node-

      # 2) Install dependencies
      - name: Install dependencies
        run: npm install
        # npm install will skip re-downloading if node_modules are already present
        # but it will still check if updates are needed

      # 3) Run tests with coverage & JUnit
      - name: Run tests with coverage & JUnit
        run: npm test  # uses the "test" script from package.json