# .github/workflows/ci.yml

name: CI - Validate & Report Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # or 18, etc.

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage & JUnit
        run: npm test  # uses the "test" script from package.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: test-results/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
            
